name: flutter_youtube_downloader
description: A flutter plugin for extracting and downloading youtube video url
version: 0.0.5
homepage: https://github.com/Destiny-Ed/flutter_youtube_downloader

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.destinyed.flutter_youtube_downloader
        pluginClass: FlutterYoutubeDownloaderPlugin
      ios:
        pluginClass: FlutterYoutubeDownloaderPlugin