name: flutter_youtube_downloader_example
description: Demonstrates how to use the flutter_youtube_downloader plugin.

publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  flutter_youtube_downloader:
    path: ../

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
